<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [ 'name' => 'Ayon', 'email' => 'smunt@munni.com', 'username'=>'ayon', 'password' => Hash::make('123456'), 'user_type' => '1', 'mobile_number' => '01191111606', 'created_at' => date('Y-m-d H:i:s')],
            [ 'name' => 'Munni', 'email' => 'munty@munni.com', 'username'=>'munni', 'password' => Hash::make('123456'), 'user_type' => '2', 'mobile_number' => '01191111606', 'created_at' => date('Y-m-d H:i:s')],
            [ 'name' => 'Auro', 'email' => 'smt@mmun.com', 'username'=>'auro', 'password' => Hash::make('123456'), 'user_type' => '1', 'mobile_number' => '01191111606', 'created_at' => date('Y-m-d H:i:s')],
            [ 'name' => 'Munna', 'email' => 'mnty@munna.com', 'username'=>'munna', 'password' => Hash::make('123456'), 'user_type' => '2', 'mobile_number' => '01191111606', 'created_at' => date('Y-m-d H:i:s')],
        ]);
        DB::table('freelancers')->insert([
            [ 'user_id' => '1', 'spec' => 'Photographer', 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '3', 'spec' => 'Makeup Artist', 'created_at' => date('Y-m-d H:i:s')],
        ]);
        DB::table('employers')->insert([
            [ 'user_id' => '2','created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '4','created_at' => date('Y-m-d H:i:s')],
        ]);
        DB::table('jobs')->insert([
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
            [ 'user_id' => '2', 'job_title' => 'Need a photographer', 'job_category' => 'Photography', 'job_address' => 'Dhaka', 'job_description' => '{Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores aperiam mollitia nesciunt sapiente alias voluptatum asperiores porro nemo veritatis pariatur cum magnam ab debitis officia accusantium minima provident, ipsa dicta?', 'job_budget' =>'5000', 'job_date' => '2021-10-10', 'job_status' => "unassigned", 'created_at' => date('Y-m-d H:i:s')],
                

        ]);

            
    }
}
